#+title: Toolkit for working with Yandex Metrika data via Logs API

* Description

Toolkit for working with non-aggregated Yandex Metrika data via Logs API. Official API documentation is available [[https://yandex.com/dev/metrika/en/logs/][here]].

* Installation

1. Clone the repository:

   #+begin_src sh
     git clone https://github.com/keatumal/yandex-metrika-logs.git
     cd yandex-metrika-logs
   #+end_src

2. Install dependencies:

   Using [[https://github.com/astral-sh/uv][uv]]:

   #+begin_src sh
     uv sync
   #+end_src

   Or via =pip=:

   #+begin_src sh
  pip install -r requirements.txt
  #+end_src

* Usage

1. Create ~.env~ (description below, example in ~.env.example~)
2. Create ~src/config.py~ (description below, example in ~src/config_example.py~)
3. Run the required script:

   Via =uv=:

      #+begin_src sh
        uv run src/scripts/<script_name.py>
      #+end_src

   Or, if installed via =pip=:
   
     #+begin_src
     python src/scripts/<script_name.py>
     #+end_src

* Scripts

Located in the ~src/scripts~ directory and can be run from anywhere. Each script has help on arguments and usage via =-h, --help=.

** =download_logs.py=

Allows you to request and/or download reports. Reports cannot be requested for the current day or for a period longer than a year.

** =reports.py=

Allows you to display a list of ready reports and delete them. The script *does not request* confirmation for deletion.

* Configuration

Is set in the ~.env~ and ~src/config.py~ files.

** ~.env~

- =YM_AUTH_TOKEN=: OAuth token. How to get it is [[https://yandex.com/dev/metrika/en/intro/authorization][described by Yandex]].

** ~src/config.py~

All parameters listed below are required, default values are not currently provided.

- =WAIT_INTERVAL=: this is the interval in seconds between checks for report readiness.
- =ATTRIBUTION_MODEL=: default attribution model. A list of possible values can be viewed, for example, [[https://yandex.ru/dev/metrika/en/logs/openapi/getLogRequests][here]].
- =FIELDS_MAP=: Fields that we request in the report. The key (before the colon) is the field name for the API, and the value (after the colon) is its final name in the file.

  By default, it currently contains a large list of fields for user visits. Additional ones can be found in the [[https://yandex.com/dev/metrika/en/logs/fields/hits][documentation]].

* License

This project is distributed under the MIT license. See the LICENSE file for details.

* Contacts

If you have any questions or suggestions, contact me via Telegram: https://t.me/anakvad
