# Report readiness check interval (seconds)
WAIT_INTERVAL = 10

# https://yandex.com/dev/metrika/en/logs/fields/visits
# https://yandex.com/dev/metrika/en/logs/fields/hits
FIELDS_MAP = {
    'ym:s:visitID': 'visitID',
    'ym:s:date': 'date',
    'ym:s:dateTime': 'dateTime',
    'ym:s:dateTimeUTC': 'dateTimeUTC',
    'ym:s:isNewUser': 'isNewUser',
    'ym:s:startURL': 'startURL',
    'ym:s:endURL': 'endURL',
    'ym:s:pageViews': 'pageViews',
    'ym:s:visitDuration': 'visitDuration',
    'ym:s:bounce': 'bounce',
    'ym:s:ipAddress': 'ipAddress',
    'ym:s:regionCountry': 'regionCountry',
    'ym:s:regionCity': 'regionCity',
    'ym:s:regionCountryID': 'regionCountryID',
    'ym:s:regionCityID': 'regionCityID',
    'ym:s:clientID': 'clientID',
    'ym:s:counterUserIDHash': 'counterUserIDHash',
    'ym:s:goalsID': 'goalsID',
    'ym:s:goalsSerialNumber': 'goalsSerialNumber',
    'ym:s:goalsDateTime': 'goalsDateTime',
    'ym:s:goalsPrice': 'goalsPrice',
    'ym:s:goalsOrder': 'goalsOrder',
    'ym:s:goalsCurrency': 'goalsCurrency',
    'ym:s:referer': 'referer',

    'ym:s:cross_device_firstTrafficSource': 'firstTrafficSource',
    'ym:s:cross_device_lastTrafficSource': 'lastTrafficSource',
    'ym:s:cross_device_last_significantTrafficSource': 'lastsignTrafficSource',

    'ym:s:cross_device_firstAdvEngine': 'firstAdvEngine',
    'ym:s:cross_device_lastAdvEngine': 'lastAdvEngine',
    'ym:s:cross_device_last_significantAdvEngine': 'lastsignAdvEngine',

    'ym:s:cross_device_firstReferalSource': 'firstReferalSource',
    'ym:s:cross_device_lastReferalSource': 'lastReferalSource',
    'ym:s:cross_device_last_significantReferalSource': 'lastsignReferalSource',

    'ym:s:cross_device_firstSearchEngineRoot': 'firstSearchEngineRoot',
    'ym:s:cross_device_lastSearchEngineRoot': 'lastSearchEngineRoot',
    'ym:s:cross_device_last_significantSearchEngineRoot': 'lastsignSearchEngineRoot',

    'ym:s:cross_device_firstSearchEngine': 'firstSearchEngine',
    'ym:s:cross_device_lastSearchEngine': 'lastSearchEngine',
    'ym:s:cross_device_last_significantSearchEngine': 'lastsignSearchEngine',

    'ym:s:cross_device_firstSocialNetwork': 'firstSocialNetwork',
    'ym:s:cross_device_lastSocialNetwork': 'lastSocialNetwork',
    'ym:s:cross_device_last_significantSocialNetwork': 'lastsignSocialNetwork',

    'ym:s:cross_device_firstSocialNetworkProfile': 'firstSocialNetworkProfile',
    'ym:s:cross_device_lastSocialNetworkProfile': 'lastSocialNetworkProfile',
    'ym:s:cross_device_last_significantSocialNetworkProfile': 'lastsignSocialNetworkProfile',

    'ym:s:cross_device_last_yandex_direct_clickDirectClickOrder': 'DirectClickOrder',
    'ym:s:cross_device_last_yandex_direct_clickDirectBannerGroup': 'DirectBannerGroup',
    'ym:s:cross_device_last_yandex_direct_clickDirectClickBanner': 'DirectClickBanner',
    'ym:s:cross_device_last_yandex_direct_clickDirectClickOrderName': 'DirectClickOrderName',
    'ym:s:cross_device_last_yandex_direct_clickClickBannerGroupName': 'ClickBannerGroupName',
    'ym:s:cross_device_last_yandex_direct_clickDirectClickBannerName': 'DirectClickBannerName',
    'ym:s:cross_device_last_yandex_direct_clickDirectPlatformType': 'DirectPlatformType',
    'ym:s:cross_device_last_yandex_direct_clickDirectPlatform': 'DirectPlatform',

    'ym:s:cross_device_firstUTMCampaign': 'firstUTMCampaign',
    'ym:s:cross_device_lastUTMCampaign': 'lastUTMCampaign',
    'ym:s:cross_device_last_significantUTMCampaign': 'lastsignUTMCampaign',
    'ym:s:cross_device_firstUTMContent': 'firstUTMContent',
    'ym:s:cross_device_lastUTMContent': 'lastUTMContent',
    'ym:s:cross_device_last_significantUTMContent': 'lastsignUTMContent',
    'ym:s:cross_device_firstUTMMedium': 'firstUTMMedium',
    'ym:s:cross_device_lastUTMMedium': 'lastUTMMedium',
    'ym:s:cross_device_last_significantUTMMedium': 'lastsignUTMMedium',
    'ym:s:cross_device_firstUTMSource': 'firstUTMSource',
    'ym:s:cross_device_lastUTMSource': 'lastUTMSource',
    'ym:s:cross_device_last_significantUTMSource': 'lastsignUTMSource',
    'ym:s:cross_device_firstUTMTerm': 'firstUTMTerm',
    'ym:s:cross_device_lastUTMTerm': 'lastUTMTerm',
    'ym:s:cross_device_last_significantUTMTerm': 'lastsignUTMTerm',

    'ym:s:browserLanguage': 'browserLanguage',
    'ym:s:browserCountry': 'browserCountry',
    'ym:s:deviceCategory': 'deviceCategory',
    'ym:s:mobilePhone': 'mobilePhone',
    'ym:s:mobilePhoneModel': 'mobilePhoneModel',
    'ym:s:operatingSystemRoot': 'operatingSystemRoot',
    'ym:s:operatingSystem': 'operatingSystem',
    'ym:s:browser': 'browser',
    'ym:s:browserMajorVersion': 'browserMajorVersion',
    'ym:s:browserMinorVersion': 'browserMinorVersion',
    'ym:s:browserEngine': 'browserEngine',
    'ym:s:cookieEnabled': 'cookieEnabled',
    'ym:s:javascriptEnabled': 'javascriptEnabled',

    'ym:s:cross_device_firstRecommendationSystem': 'firstRecommendationSystem',
    'ym:s:cross_device_lastRecommendationSystem': 'lastRecommendationSystem',
    'ym:s:cross_device_last_significantRecommendationSystem': 'lastsignRecommendationSystem',
    'ym:s:cross_device_firstMessenger': 'firstMessenger',
    'ym:s:cross_device_lastMessenger': 'lastMessenger',
    'ym:s:cross_device_last_significantMessenger': 'lastsignMessenger',
}