from utils.utils import populate_with_attribution

# Report readiness check interval (seconds)
WAIT_INTERVAL = 10

# https://yandex.com/dev/metrika/en/logs/param
#
# first, last, lastsign, last_yandex_direct_click, automatic
# cross_device_first, cross_device_last, cross_device_last_significant,
# cross_device_last_yandex_direct_click
DEFAULT_ATTRIBUTION_MODEL = "cross_device_last_significant"

# visits, hits
DOWNLOAD_SOURCE = "visits"

# Lists of available fields:
#
# https://yandex.com/dev/metrika/en/logs/fields/visits
# https://yandex.com/dev/metrika/en/logs/fields/hits

# `download_logs.py` will order a report for these fields
DOWNLOAD_FIELDS = [
    "ym:s:visitID",
    "ym:s:date",
    "ym:s:dateTime",
    "ym:s:dateTimeUTC",
    "ym:s:isNewUser",
    "ym:s:startURL",
    "ym:s:endURL",
    "ym:s:pageViews",
    "ym:s:visitDuration",
    "ym:s:bounce",
    "ym:s:ipAddress",
    "ym:s:regionCountry",
    "ym:s:regionCity",
    "ym:s:regionCountryID",
    "ym:s:regionCityID",
    "ym:s:clientID",
    "ym:s:counterUserIDHash",
    "ym:s:goalsID",
    "ym:s:goalsSerialNumber",
    "ym:s:goalsDateTime",
    "ym:s:goalsPrice",
    "ym:s:goalsOrder",
    "ym:s:goalsCurrency",
    "ym:s:referer",
    "ym:s:<attr>TrafficSource",
    "ym:s:<attr>AdvEngine",
    "ym:s:<attr>ReferalSource",
    "ym:s:<attr>SearchEngineRoot",
    "ym:s:<attr>SearchEngine",
    "ym:s:<attr>SocialNetwork",
    "ym:s:<attr>SocialNetworkProfile",
    "ym:s:<attr>RecommendationSystem",
    "ym:s:<attr>Messenger",
    "ym:s:cross_device_last_yandex_direct_clickDirectClickOrder",
    "ym:s:cross_device_last_yandex_direct_clickDirectBannerGroup",
    "ym:s:cross_device_last_yandex_direct_clickDirectClickBanner",
    "ym:s:cross_device_last_yandex_direct_clickDirectClickOrderName",
    "ym:s:cross_device_last_yandex_direct_clickClickBannerGroupName",
    "ym:s:cross_device_last_yandex_direct_clickDirectClickBannerName",
    "ym:s:cross_device_last_yandex_direct_clickDirectPlatformType",
    "ym:s:cross_device_last_yandex_direct_clickDirectPlatform",
    "ym:s:<attr>UTMCampaign",
    "ym:s:<attr>UTMContent",
    "ym:s:<attr>UTMMedium",
    "ym:s:<attr>UTMSource",
    "ym:s:<attr>UTMTerm",
    "ym:s:browserLanguage",
    "ym:s:browserCountry",
    "ym:s:deviceCategory",
    "ym:s:mobilePhone",
    "ym:s:mobilePhoneModel",
    "ym:s:operatingSystemRoot",
    "ym:s:operatingSystem",
    "ym:s:browser",
    "ym:s:browserMajorVersion",
    "ym:s:browserMinorVersion",
    "ym:s:browserEngine",
    "ym:s:cookieEnabled",
    "ym:s:javascriptEnabled",
]

# Dictionary for renaming attribution models
ATTRIBUTION_MAPPING = {
    "first": "first",
    "last": "last",
    "lastsign": "lastsign",
    "last_yandex_direct_click": "lastYD",
    "cross_device_first": "crossFirst",
    "cross_device_last": "crossLast",
    "cross_device_last_significant": "crossLastSign",
    "cross_device_last_yandex_direct_click": "crossLastYD",
    "automatic": "auto",
}

# Dictionary for renaming visit fields
VISITS_FIELDS_MAPPING = {
    "ym:s:visitID": "visitID",
    "ym:s:counterID": "counterID",
    "ym:s:watchIDs": "watchIds",
    "ym:s:date": "date",
    "ym:s:dateTime": "dateTime",
    "ym:s:dateTimeUTC": "dateTimeUTC",
    "ym:s:isNewUser": "isNewUser",
    "ym:s:startURL": "startURL",
    "ym:s:endURL": "endURL",
    "ym:s:pageViews": "pageViews",
    "ym:s:visitDuration": "visitDuration",
    "ym:s:bounce": "bounce",
    "ym:s:ipAddress": "ipAddress",
    "ym:s:regionCountry": "regionCountry",
    "ym:s:regionCity": "regionCity",
    "ym:s:regionCountryID": "regionCountryID",
    "ym:s:regionCityID": "regionCityID",
    "ym:s:clientID": "clientID",
    "ym:s:counterUserIDHash": "counterUserIDHash",
    "ym:s:networkType": "networkType",
    "ym:s:goalsID": "goalsID",
    "ym:s:goalsSerialNumber": "goalsSerialNumber",
    "ym:s:goalsDateTime": "goalsDateTime",
    "ym:s:goalsPrice": "goalsPrice",
    "ym:s:goalsOrder": "goalsOrder",
    "ym:s:goalsCurrency": "goalsCurrency",
    "ym:s:<attr>TrafficSource": "<attr>TrafficSource",
    "ym:s:<attr>AdvEngine": "<attr>AdvEngine",
    "ym:s:<attr>ReferalSource": "<attr>ReferalSource",
    "ym:s:<attr>SearchEngineRoot": "<attr>SearchEngineRoot",
    "ym:s:<attr>SearchEngine": "<attr>SearchEngine",
    "ym:s:<attr>SocialNetwork": "<attr>SocialNetwork",
    "ym:s:<attr>SocialNetworkProfile": "<attr>SocialNetworkProfile",
    "ym:s:referer": "referer",
    "ym:s:<attr>DirectClickOrder": "<attr>DirectClickOrder",
    "ym:s:<attr>DirectBannerGroup": "<attr>DirectBannerGroup",
    "ym:s:<attr>DirectClickBanner": "<attr>DirectClickBanner",
    "ym:s:<attr>DirectClickOrderName": "<attr>DirectClickOrderName",
    "ym:s:<attr>ClickBannerGroupName": "<attr>ClickBannerGroupName",
    "ym:s:<attr>DirectClickBannerName": "<attr>DirectClickBannerName",
    "ym:s:<attr>DirectPhraseOrCond": "<attr>DirectPhraseOrCond",
    "ym:s:<attr>DirectPlatformType": "<attr>DirectPlatformType",
    "ym:s:<attr>DirectPlatform": "<attr>DirectPlatform",
    "ym:s:<attr>DirectConditionType": "<attr>DirectConditionType",
    "ym:s:<attr>CurrencyID": "<attr>CurrencyId",
    "ym:s:from": "from",
    "ym:s:<attr>UTMCampaign": "<attr>UTMCampaign",
    "ym:s:<attr>UTMContent": "<attr>UTMContent",
    "ym:s:<attr>UTMMedium": "<attr>UTMMedium",
    "ym:s:<attr>UTMSource": "<attr>UTMSource",
    "ym:s:<attr>UTMTerm": "<attr>UTMTerm",
    "ym:s:<attr>openstatAd": "<attr>openstatAd",
    "ym:s:<attr>openstatCampaign": "<attr>openstatCampaign",
    "ym:s:<attr>openstatService": "<attr>openstatService",
    "ym:s:<attr>openstatSource": "<attr>openstatSource",
    "ym:s:<attr>hasGCLID": "<attr>hasGCLID",
    "ym:s:<attr>GCLID": "<attr>GCLID",
    "ym:s:browserLanguage": "browserLanguage",
    "ym:s:browserCountry": "browserCountry",
    "ym:s:clientTimeZone": "clientTimeZone",
    "ym:s:deviceCategory": "deviceCategory",
    "ym:s:mobilePhone": "mobilePhone",
    "ym:s:mobilePhoneModel": "mobilePhoneModel",
    "ym:s:operatingSystemRoot": "operatingSystemRoot",
    "ym:s:operatingSystem": "operatingSystem",
    "ym:s:browser": "browser",
    "ym:s:browserMajorVersion": "browserMajorVersion",
    "ym:s:browserMinorVersion": "browserMinorVersion",
    "ym:s:browserEngine": "browserEngine",
    "ym:s:browserEngineVersion1": "browserEngineVersion1",
    "ym:s:browserEngineVersion2": "browserEngineVersion2",
    "ym:s:browserEngineVersion3": "browserEngineVersion3",
    "ym:s:browserEngineVersion4": "browserEngineVersion4",
    "ym:s:cookieEnabled": "cookieEnabled",
    "ym:s:javascriptEnabled": "javascriptEnabled",
    "ym:s:screenFormat": "screenFormat",
    "ym:s:screenColors": "screenColors",
    "ym:s:screenOrientation": "screenOrientation",
    "ym:s:screenOrientationName": "screenOrientationName",
    "ym:s:screenWidth": "screenWidth",
    "ym:s:screenHeight": "screenHeight",
    "ym:s:physicalScreenWidth": "physicalScreenWidth",
    "ym:s:physicalScreenHeight": "physicalScreenHeight",
    "ym:s:windowClientWidth": "windowClientWidth",
    "ym:s:windowClientHeight": "windowClientHeight",
    "ym:s:purchaseID": "purchaseID",
    "ym:s:purchaseDateTime": "purchaseDateTime",
    "ym:s:purchaseAffiliation": "purchaseAffiliation",
    "ym:s:purchaseRevenue": "purchaseRevenue",
    "ym:s:purchaseTax": "purchaseTax",
    "ym:s:purchaseShipping": "purchaseShipping",
    "ym:s:purchaseCoupon": "purchaseCoupon",
    "ym:s:purchaseCurrency": "purchaseCurrency",
    "ym:s:purchaseProductQuantity": "purchaseProductQuantity",
    "ym:s:eventsProductID": "eventsProductID",
    "ym:s:eventsProductList": "eventsProductList",
    "ym:s:eventsProductBrand": "eventsProductBrand",
    "ym:s:eventsProductCategory": "eventsProductCategory",
    "ym:s:eventsProductCategory1": "eventsProductCategory1",
    "ym:s:eventsProductCategory2": "eventsProductCategory2",
    "ym:s:eventsProductCategory3": "eventsProductCategory3",
    "ym:s:eventsProductCategory4": "eventsProductCategory4",
    "ym:s:eventsProductCategory5": "eventsProductCategory5",
    "ym:s:eventsProductVariant": "eventsProductVariant",
    "ym:s:eventsProductPosition": "eventsProductPosition",
    "ym:s:eventsProductPrice": "eventsProductPrice",
    "ym:s:eventsProductCurrency": "eventsProductCurrency",
    "ym:s:eventsProductCoupon": "eventsProductCoupon",
    "ym:s:eventsProductQuantity": "eventsProductQuantity",
    "ym:s:eventsProductEventTime": "eventsProductEventTime",
    "ym:s:eventsProductType": "eventsProductType",
    "ym:s:eventsProductDiscount": "eventsProductDiscount",
    "ym:s:eventsProductName": "eventsProductName",
    "ym:s:productsPurchaseID": "productsPurchaseID",
    "ym:s:productsID": "productsID",
    "ym:s:productsName": "productsName",
    "ym:s:productsBrand": "productsBrand",
    "ym:s:productsCategory": "productsCategory",
    "ym:s:productsCategory1": "productsCategory1",
    "ym:s:productsCategory2": "productsCategory2",
    "ym:s:productsCategory3": "productsCategory3",
    "ym:s:productsCategory4": "productsCategory4",
    "ym:s:productsCategory5": "productsCategory5",
    "ym:s:productsVariant": "productsVariant",
    "ym:s:productsPosition": "productsPosition",
    "ym:s:productsPrice": "productsPrice",
    "ym:s:productsCurrency": "productsCurrency",
    "ym:s:productsCoupon": "productsCoupon",
    "ym:s:productsQuantity": "productsQuantity",
    "ym:s:productsList": "productsList",
    "ym:s:productsEventTime": "productsEventTime",
    "ym:s:productsDiscount": "productsDiscount",
    "ym:s:impressionsURL": "impressionsURL",
    "ym:s:impressionsDateTime": "impressionsDateTime",
    "ym:s:impressionsProductID": "impressionsProductID",
    "ym:s:impressionsProductName": "impressionsProductName",
    "ym:s:impressionsProductBrand": "impressionsProductBrand",
    "ym:s:impressionsProductCategory": "impressionsProductCategory",
    "ym:s:impressionsProductCategory1": "impressionsProductCategory1",
    "ym:s:impressionsProductCategory2": "impressionsProductCategory2",
    "ym:s:impressionsProductCategory3": "impressionsProductCategory3",
    "ym:s:impressionsProductCategory4": "impressionsProductCategory4",
    "ym:s:impressionsProductCategory5": "impressionsProductCategory5",
    "ym:s:impressionsProductVariant": "impressionsProductVariant",
    "ym:s:impressionsProductPrice": "impressionsProductPrice",
    "ym:s:impressionsProductCurrency": "impressionsProductCurrency",
    "ym:s:impressionsProductCoupon": "impressionsProductCoupon",
    "ym:s:impressionsProductList": "impressionsProductList",
    "ym:s:impressionsProductQuantity": "impressionsProductQuantity",
    "ym:s:impressionsProductEventTime": "impressionsProductEventTime",
    "ym:s:impressionsProductDiscount": "impressionsProductDiscount",
    "ym:s:promotionID": "promotionID",
    "ym:s:promotionName": "promotionName",
    "ym:s:promotionCreative": "promotionCreative",
    "ym:s:promotionPosition": "promotionPosition",
    "ym:s:promotionCreativeSlot": "promotionCreativeSlot",
    "ym:s:promotionEventTime": "promotionEventTime",
    "ym:s:promotionType": "promotionType",
    "ym:s:offlineCallTalkDuration": "offlineCallTalkDuration",
    "ym:s:offlineCallHoldDuration": "offlineCallHoldDuration",
    "ym:s:offlineCallMissed": "offlineCallMissed",
    "ym:s:offlineCallTag": "offlineCallTag",
    "ym:s:offlineCallFirstTimeCaller": "offlineCallFirstTimeCaller",
    "ym:s:offlineCallURL": "offlineCallURL",
    "ym:s:parsedParamsKey1": "parsedParamsKey1",
    "ym:s:parsedParamsKey2": "parsedParamsKey2",
    "ym:s:parsedParamsKey3": "parsedParamsKey3",
    "ym:s:parsedParamsKey4": "parsedParamsKey4",
    "ym:s:parsedParamsKey5": "parsedParamsKey5",
    "ym:s:parsedParamsKey6": "parsedParamsKey6",
    "ym:s:parsedParamsKey7": "parsedParamsKey7",
    "ym:s:parsedParamsKey8": "parsedParamsKey8",
    "ym:s:parsedParamsKey9": "parsedParamsKey9",
    "ym:s:parsedParamsKey10": "parsedParamsKey10",
    "ym:s:<attr>RecommendationSystem": "<attr>RecommendationSystem",
    "ym:s:<attr>Messenger": "<attr>Messenger",
}

# Dictionary for renaming events (hits) fields
EVENT_FIELDS_MAPPING = {
    "ym:pv:watchID": "watchID",
    "ym:pv:pageViewID": "pageViewID",
    "ym:pv:counterID": "counterID",
    "ym:pv:clientID": "clientID",
    "ym:pv:counterUserIDHash": "counterUserIDHash",
    "ym:pv:date": "date",
    "ym:pv:dateTime": "dateTime",
    "ym:pv:title": "title",
    "ym:pv:pageCharset": "pageCharset",
    "ym:pv:goalsID": "goalsID",
    "ym:pv:URL": "URL",
    "ym:pv:referer": "referer",
    "ym:pv:UTMCampaign": "UTMCampaign",
    "ym:pv:UTMContent": "UTMContent",
    "ym:pv:UTMMedium": "UTMMedium",
    "ym:pv:UTMSource": "UTMSource",
    "ym:pv:UTMTerm": "UTMTerm",
    "ym:pv:openstatAd": "openstatAd",
    "ym:pv:openstatCampaign": "openstatCampaign",
    "ym:pv:openstatService": "openstatService",
    "ym:pv:openstatSource": "openstatSource",
    "ym:pv:operatingSystem": "operatingSystem",
    "ym:pv:from": "from",
    "ym:pv:hasGCLID": "hasGCLID",
    "ym:pv:GCLID": "GCLID",
    "ym:pv:lastTrafficSource": "lastTrafficSource",
    "ym:pv:lastSearchEngineRoot": "lastSearchEngineRoot",
    "ym:pv:lastSearchEngine": "lastSearchEngine",
    "ym:pv:lastAdvEngine": "lastAdvEngine",
    "ym:pv:lastSocialNetwork": "lastSocialNetwork",
    "ym:pv:lastSocialNetworkProfile": "lastSocialNetworkProfile",
    "ym:pv:recommendationSystem": "recommendationSystem",
    "ym:pv:messenger": "messenger",
    "ym:pv:browser": "browser",
    "ym:pv:browserMajorVersion": "browserMajorVersion",
    "ym:pv:browserMinorVersion": "browserMinorVersion",
    "ym:pv:browserCountry": "browserCountry",
    "ym:pv:browserEngine": "browserEngine",
    "ym:pv:browserEngineVersion1": "browserEngineVersion1",
    "ym:pv:browserEngineVersion2": "browserEngineVersion2",
    "ym:pv:browserEngineVersion3": "browserEngineVersion3",
    "ym:pv:browserEngineVersion4": "browserEngineVersion4",
    "ym:pv:browserLanguage": "browserLanguage",
    "ym:pv:clientTimeZone": "clientTimeZone",
    "ym:pv:cookieEnabled": "cookieEnabled",
    "ym:pv:deviceCategory": "deviceCategory",
    "ym:pv:javascriptEnabled": "javascriptEnabled",
    "ym:pv:mobilePhone": "mobilePhone",
    "ym:pv:mobilePhoneModel": "mobilePhoneModel",
    "ym:pv:operatingSystemRoot": "operatingSystemRoot",
    "ym:pv:physicalScreenHeight": "physicalScreenHeight",
    "ym:pv:physicalScreenWidth": "physicalScreenWidth",
    "ym:pv:screenColors": "screenColors",
    "ym:pv:screenFormat": "screenFormat",
    "ym:pv:screenHeight": "screenHeight",
    "ym:pv:screenOrientation": "screenOrientation",
    "ym:pv:screenOrientationName": "screenOrientationName",
    "ym:pv:screenWidth": "screenWidth",
    "ym:pv:windowClientHeight": "windowClientHeight",
    "ym:pv:windowClientWidth": "windowClientWidth",
    "ym:pv:ipAddress": "ipAddress",
    "ym:pv:regionCity": "regionCity",
    "ym:pv:regionCountry": "regionCountry",
    "ym:pv:regionCityID": "regionCityID",
    "ym:pv:regionCountryID": "regionCountryID",
    "ym:pv:isPageView": "isPageView",
    "ym:pv:isTurboPage": "isTurboPage",
    "ym:pv:isTurboApp": "isTurboApp",
    "ym:pv:iFrame": "iFrame",
    "ym:pv:link": "link",
    "ym:pv:download": "download",
    "ym:pv:notBounce": "notBounce",
    "ym:pv:artificial": "artificial",
    "ym:pv:ecommerce": "ecommerce",
    "ym:pv:params": "params",
    "ym:pv:parsedParamsKey1": "parsedParamsKey1",
    "ym:pv:parsedParamsKey2": "parsedParamsKey2",
    "ym:pv:parsedParamsKey3": "parsedParamsKey3",
    "ym:pv:parsedParamsKey4": "parsedParamsKey4",
    "ym:pv:parsedParamsKey5": "parsedParamsKey5",
    "ym:pv:parsedParamsKey6": "parsedParamsKey6",
    "ym:pv:parsedParamsKey7": "parsedParamsKey7",
    "ym:pv:parsedParamsKey8": "parsedParamsKey8",
    "ym:pv:parsedParamsKey9": "parsedParamsKey9",
    "ym:pv:parsedParamsKey10": "parsedParamsKey10",
    "ym:pv:httpError": "httpError",
    "ym:pv:networkType": "networkType",
    "ym:pv:shareService": "shareService",
    "ym:pv:shareURL": "shareURL",
    "ym:pv:shareTitle": "shareTitle",
}

# It's best not to touch it. The code is needed to replace `<attr>` with combinations of
# all attribution models in renaming dictionaries.
VISITS_FIELDS_MAPPING = populate_with_attribution(
    VISITS_FIELDS_MAPPING, ATTRIBUTION_MAPPING
)
EVENT_FIELDS_MAPPING = populate_with_attribution(
    EVENT_FIELDS_MAPPING, ATTRIBUTION_MAPPING
)
